version: "3"
services:
    frontend:
        image: briansokoloski/golffrontend:latest
        ports:
            - "3000:3000"
        restart: always

    backend:
        image: briansokoloski/golfbackend:latest
        ports:
            - "8082:8082"
        volumes:
            - ${DATABASE_LOCATION}:/app/data
        restart: always
volumes:
    backend-data:
